import type { FunctionDefinition } from '../interfaces';

export const DEFAULT_FUNCTIONS: FunctionDefinition[] = [
  {
    name: 'min',
    arguments: ['#f'],
    category: 'math',
    description: 'Мінімальне значення поля',
    signature: 'min(#f)',
    sqlName: 'MIN',
  },
  {
    name: 'max',
    arguments: ['#f'],
    category: 'math',
    description: 'Максимальне значення поля',
    signature: 'max(#f)',
    sqlName: 'MAX',
  },
  {
    name: 'avg',
    arguments: ['#f'],
    category: 'math',
    description: 'Середнє значення поля',
    signature: 'avg(#f)',
    sqlName: 'AVG',
  },
  {
    name: 'sum',
    arguments: ['#f'],
    category: 'math',
    description: 'Сума значень поля',
    signature: 'sum(#f)',
    sqlName: 'SUM',
  },
  {
    name: 'count',
    arguments: ['#f'],
    category: 'math',
    description: 'Кількість записів по полю',
    signature: 'count(#f)',
    sqlName: 'COUNT',
  },
  {
    name: 'round',
    arguments: ['#f', 'decimals'],
    category: 'math',
    description: 'Округлення до вказаної кількості знаків',
    signature: 'round(#f, decimals)',
    sqlName: 'ROUND',
  },
  {
    name: 'ceil',
    arguments: ['#f'],
    category: 'math',
    description: 'Округлення числа вгору',
    signature: 'ceil(#f)',
    sqlName: 'CEIL',
  },
  {
    name: 'floor',
    arguments: ['#f'],
    category: 'math',
    description: 'Округлення числа вниз',
    signature: 'floor(#f)',
    sqlName: 'FLOOR',
  },
  {
    name: 'concat',
    arguments: ['#f1', '#f2'],
    category: 'string',
    description: 'Конкатенація рядків',
    signature: 'concat(#f1, #f2, ...)',
    sqlName: 'CONCAT',
  },
  {
    name: 'length',
    arguments: ['#f'],
    category: 'string',
    description: 'Довжина рядка',
    signature: 'length(#f)',
    sqlName: 'LENGTH',
  },
  {
    name: 'upper',
    arguments: ['#f'],
    category: 'string',
    description: 'Верхній регістр',
    signature: 'upper(#f)',
    sqlName: 'UPPER',
  },
  {
    name: 'lower',
    arguments: ['#f'],
    category: 'string',
    description: 'Нижній регістр',
    signature: 'lower(#f)',
    sqlName: 'LOWER',
  },
  {
    name: 'substring',
    arguments: ['#f', 'start_index', 'length'],
    category: 'string',
    description: 'Підрядок',
    signature: 'substring(#f, start_index, length)',
    sqlName: 'SUBSTRING',
  },
  {
    name: 'left',
    arguments: ['#f', 'length'],
    category: 'string',
    description: 'Ліва частина рядка',
    signature: 'left(#f, length)',
    sqlName: 'LEFT',
  },
  {
    name: 'right',
    arguments: ['#f', 'length'],
    category: 'string',
    description: 'Права частина рядка',
    signature: 'right(#f, length)',
    sqlName: 'RIGHT',
  },
  { name: 'now', arguments: undefined, category: 'date', description: 'Поточна дата і час', signature: 'now()' },
  { name: 'today', arguments: undefined, category: 'date', description: 'Поточна дата', signature: 'today()' },
  {
    name: 'date',
    arguments: ['#f'],
    category: 'date',
    description: 'Дата з поля',
    signature: 'date(#f)',
    sqlName: 'DATE',
  },
  { name: 'month', arguments: undefined, category: 'date', description: 'Поточний місяць', signature: 'month()' },
  { name: 'month', arguments: ['#f'], category: 'date', description: 'Місяць з поля дати', signature: 'month(#f)' },
  { name: 'year', arguments: undefined, category: 'date', description: 'Поточний рік', signature: 'year()' },
  { name: 'year', arguments: ['#f'], category: 'date', description: 'Рік з поля дати', signature: 'year(#f)' },
];
